---
name: "✨ Feature Request"
description: "提交新功能或改进建议"
title: "[FEATURE] "
labels: ["enhancement"]
assignees:
  - "product-manager"  # 默认分配给产品经理

# --- 表单主体 ---
body:
  # 1. 功能概述
  - type: markdown
    attributes:
      value: "## 📌 功能概述"

  - type: textarea
    id: description
    attributes:
      label: "功能描述"
      description: "用简洁的语言说明该功能的用途和价值"
      placeholder: "例如：增加深色模式支持，减少夜间使用时的眼睛疲劳"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "解决的问题"
      description: "当前存在的痛点或未满足的需求"
      placeholder: "目前夜间使用时白色背景过于刺眼..."

  # 2. 优先级评估
  - type: markdown
    attributes:
      value: "## 🎯 优先级"

  - type: dropdown
    id: priority
    attributes:
      label: "业务优先级"
      options:
        - "P0 (核心业务关键)"
        - "P1 (提升核心体验)"
        - "P2 (锦上添花)"
      default: "P1 (提升核心体验)"
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: "影响范围"
      options:
        - label: "影响大量用户（>80%）"
        - label: "影响付费用户"
        - label: "影响管理后台"

  # 3. 技术考量
  - type: markdown
    attributes:
      value: "## ⚙️ 技术实现"

  - type: textarea
    id: proposal
    attributes:
      label: "实现方案建议"
      description: "可选，如果你有技术实现思路请说明"
      placeholder: "可通过 prefers-color-scheme CSS 媒体查询实现..."

  - type: checkboxes
    id: dependencies
    attributes:
      label: "依赖项"
      options:
        - label: "需要第三方服务（需说明）"
        - label: "需要设计资源"
        - label: "需要后端API修改"

  - type: textarea
    id: thirdparty
    attributes:
      label: "第三方服务详情"
      conditional: "dependencies.includes('需要第三方服务（需说明）')"
      placeholder: "例如：需要接入支付宝刷脸认证"

  # 4. 可视化参考
  - type: markdown
    attributes:
      value: "## 🎨 设计参考"

  - type: input
    id: figma
    attributes:
      label: "Figma 链接"
      placeholder: "https://figma.com/file/..."

  - type: checkboxes
    id: attachments
    attributes:
      label: "附加材料"
      options:
        - label: "竞品截图"
        - label: "手绘草图"
        - label: "用户调研数据"

  # 5. 确认声明
  - type: markdown
    attributes:
      value: "## ✅ 确认清单"

  - type: checkboxes
    id: checks
    attributes:
      label: ""
      options:
        - label: "我已搜索现有 Issue 确认无重复"
        - label: "该功能需求已获得团队初步认可"
        - label: "我愿意协助提供更多细节"
---
